//all of the Destinations in the system with the code as the value in order to display those Destinations in the searchForm component

const countryOptions = [
    {key: "ADL", value: "ADL", text: "Adelaide" },
    {key: "AMS", value: "AMS", text: "Amsterdam"},
    {key: "ATL", value: "ATL", text: "Atlanta"},
    {key: "BKK", value: "BKK", text: "Bangkok"},
    {key: "BNE", value: "BNE", text: "Brisbane"},
    {key: "CBR", value: "CBR", text: "Canberra"},
    {key: "CDG", value: "CDG", text: "Paris - Charles De Gaulle"},
    {key: "CNS", value: "CNS", text: "Cairns"},
    {key: "DOH", value: "DOH", text: "Doha"},
    {key: "DRW", value: "DRW", text: "Darwin"},
    {key: "DXB", value: "DXB", text: "Dubai"},
    {key: "FCO", value: "FCO", text: "Rome-Fiumicino"},
    {key: "GIG", value: "GIG", text: "Rio De Janeiro"},
    {key: "HBA", value: "HBA", text: "Hobart"},
    {key: "HEL", value: "HEL", text: "Helsinki"},
    {key: "HKG", value: "HKG", text: "Hong Kong"},
    {key: "HNL", value: "HNL", text: "Honolulu"},
    {key: "JFK", value: "JFK", text: "New York - JFK"},
    {key: "JNB", value: "JNB", text: "Johannesburg"},
    {key: "KUL", value: "KUL", text: "Kuala Lumpur"},
    {key: "LAX", value: "LAX", text: "Los Angeles"},
    {key: "LGA", value: "LGA", text: "New York - Laguardia"},
    {key: "LGW", value: "LGW", text: "London-Gatwick"},
    {key: "LHR", value: "LHR", text: "London-Heathrow"},
    {key: "MAD", value: "MAD", text: "Madrid"},
    {key: "MEL", value: "MEL", text: "Melbourne"},
    {key: "MIA", value: "MIA", text: "Miami"},
    {key: "MUC", value: "MUC", text: "Munich"},    
    {key: "NRT", value: "NRT", text: "Tokyo - Narita"},
    {key: "OOL", value: "OOL", text: "Gold Coast"},
    {key: "ORD", value: "ORD", text: "Chicago - OHare Intl."},
    {key: "ORY", value: "ORY", text: "Paris - Orly"},
    {key: "PER", value: "PER", text: "Perth"},
    {key: "SFO", value: "SFO", text: "San Francisco"},
    {key: "SIN", value: "SIN", text: "Singapore"},
    {key: "SYD", value: "SYD", text: "Sydney"},
    {key: "VIE", value: "VIE", text: "Vienna"},
    {key: "YYZ", value: "YYZ", text: "Toronto"}
  ]

  export default countryOptions;